### ISSUE TITLE
a decoder-only version of the framework might be a nice addition

### ISSUE THREAD

**Issue by mrRay** [Synopsis/Synopsis-Framework#5]
the size of the embedded framework could probably be reduced substantially if its functionality was limited to playing back decoded metadata

**Comment by vade** [comment]
I think thats a good idea.

I was thinking an Xcode scheme / target for a decode only framework version would also immediately help the Inspector (since it does not need the analysis code or API, but other 3rd party apps might). 

This could drop the trained tensor flow models, tensor flow library, necessary headers, but OpenCV is still a requirement for similarity (I know you know this just documenting publicly).

Do you see any problems with that approach?

**Comment by vade** [comment]
Fixed in ffa6f425cdcc2d891e3daf2065622a58c9e37417
